
chcp 65001
echo off

echo |set /p="1  " & TextAnalyzer.exe  "((◊□pV◊p)Λ~□p)					" 1 ~ | findstr /C:"A: In-Valid"	    & IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="2  " & TextAnalyzer.exe  "(q→~r)V(□◊qΛ~◊□p)				" 1 ~ | findstr /C:"A: In-Valid"	    & IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="3  " & TextAnalyzer.exe  "((q→~r)V(□◊qΛ~◊□p))				" 1 ~ | findstr /C:"A: In-Valid"        & IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="4  " & TextAnalyzer.exe  "( q V p )						" 1 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="5  " & TextAnalyzer.exe  "(p→◊p)							" 1 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="6  " & TextAnalyzer.exe  "((~p V □(r→◊p)) Λ ◊p)			" 1 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="7  " & TextAnalyzer.exe  "~(((~p V □(r→◊p)) Λ ◊p))			" 1 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="8  " & TextAnalyzer.exe  "(q→~r)V(□◊qΛ~◊□p)				" 1 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="9  " & TextAnalyzer.exe  "(□(p→q) Λ □(p→~q) )→ ~◊p			" 1 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="10 "  & TextAnalyzer.exe  "(q→~r)V(□◊q Λ ~◊□p)				" 1 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="11 "  & TextAnalyzer.exe  "(◊pΛ◊~q) Λ (~□q → □~p)			" 1 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="12 "  & TextAnalyzer.exe  "◊(pΛq) → (◊p Λ ◊q)				" 1 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="30 "  & TextAnalyzer.exe  "(qΛ(◊pΛ□(p→□~p)))				" 2 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="31 "  & TextAnalyzer.exe  "◊(p V q) → (◊p V ◊q)				" 2 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="32 "  & TextAnalyzer.exe  "◊□pΛ□□q							" 2 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="33 "  & TextAnalyzer.exe  "◊(p V q) → (◊p V ◊q)				" 2 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="34 "  & TextAnalyzer.exe  "(□p Λ □q) → □r					" 2 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="35 "  & TextAnalyzer.exe  "□(p→◊p)							" 2 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="36 "  & TextAnalyzer.exe  "□◊x								" 3 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="37 "  & TextAnalyzer.exe  "~(p→q)							" 3 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="38 "  & TextAnalyzer.exe  "((qV(◊pV□(p→□~q))))				" 3 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="39 "  & TextAnalyzer.exe  "□◊p								" 3 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="40 "  & TextAnalyzer.exe  "◊(p V q) → (◊p V ◊q)				" 3 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="41 "  & TextAnalyzer.exe  "□(p V q) → (□p V □q)				" 3 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="42 "  & TextAnalyzer.exe  "(p V q) V r						" 3 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="43 "  & TextAnalyzer.exe  "◊◊◊◊◊◊◊◊◊◊◊◊p					" 3 ~ | findstr /C:"A: In-Valid"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="44 "  & TextAnalyzer.exe  "□(q→(pΛq))→(□q→□(pΛq))			" 3 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="45 "  & TextAnalyzer.exe  "□p→v□(q→(pΛq))					" 4 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="46 "  & TextAnalyzer.exe  "□(p→(q→(pΛq)))					" 4 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="47 "  & TextAnalyzer.exe  "(□p→p)							" 4 ~ | findstr /C:"A: In-Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="48 "  & TextAnalyzer.exe  "◊(p V q) → (◊p V ◊q)				" 4 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="49 "  & TextAnalyzer.exe  "((p Λ q) → r) → (p → (~q V r))	" 4 ~ | findstr /C:"A: Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="50 "  & TextAnalyzer.exe  "(◊(p V q) Λ (◊p V ◊q)) V (p → ~q)" 4 ~ | findstr /C:"A: In-Valid"			& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
																							
																							
echo |set /p="51 " & TextAnalyzer.exe  "((◊□pV◊p)Λ~□p)					" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="52 " & TextAnalyzer.exe  "(q→~r)V(□◊qΛ~◊□p)				" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="53 " & TextAnalyzer.exe  "((q→~r)V(□◊qΛ~◊□p))				" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="54 " & TextAnalyzer.exe  "( q V p )						" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="55 " & TextAnalyzer.exe  "(p→◊p)							" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="56 " & TextAnalyzer.exe  "((~p V □(r→◊p)) Λ ◊p)			" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="57 " & TextAnalyzer.exe  "~(((~p V □(r→◊p)) Λ ◊p))			" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="58 " & TextAnalyzer.exe  "(q→~r)V(□◊qΛ~◊□p)				" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="59 " & TextAnalyzer.exe  "(□(p→q) Λ □(p→~q) )→ ~◊p			" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="60 " & TextAnalyzer.exe  "(q→~r)V(□◊q Λ ~◊□p)				" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="61 " & TextAnalyzer.exe  "(◊pΛ◊~q) Λ (~□q → □~p)			" 1 | findstr /C:"A: Unsatisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="62 " & TextAnalyzer.exe  "◊(pΛq) → (◊p Λ ◊q)				" 1 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="80 " & TextAnalyzer.exe  "(qΛ(◊pΛ□(p→□~p)))				" 2 | findstr /C:"A: Unsatisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="81 " & TextAnalyzer.exe  "◊(p V q) → (◊p V ◊q)				"2 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="82 " & TextAnalyzer.exe  "◊□pΛ□□q							" 2 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="83 " & TextAnalyzer.exe  "◊(p V q) → (◊p V ◊q)				" 2 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="84 " & TextAnalyzer.exe  "(□p Λ □q) → □r					" 2 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="85 " & TextAnalyzer.exe  "□(p→◊p)							" 2 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="86 " & TextAnalyzer.exe  "□◊x								" 3 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="87 " & TextAnalyzer.exe  "~(p→q)							" 3 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="88 " & TextAnalyzer.exe  "((qV(◊pV□(p→□~q))))				" 3 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="89 " & TextAnalyzer.exe  "□◊p								" 3 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="90 " & TextAnalyzer.exe  "◊(p V q) → (◊p V ◊q)				" 3 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="91 " & TextAnalyzer.exe  "□(p V q) → (□p V □q)				" 3 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="92 " & TextAnalyzer.exe  "◊◊◊◊◊◊◊◊◊◊◊◊p					" 3 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="93 " & TextAnalyzer.exe  "□(q→(pΛq))→(□q→□(pΛq))			" 3 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="94 " & TextAnalyzer.exe  "□p→v□(q→(pΛq))					" 4 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="95 " & TextAnalyzer.exe  "□(p→(q→(pΛq)))					" 4 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="96 " & TextAnalyzer.exe  "(□p→p)							" 4 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="97 " & TextAnalyzer.exe  "◊(p V q) → (◊p V ◊q)				" 4 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="98 " & TextAnalyzer.exe  "((p Λ q) → r) → (p → (~q V r))	" 4 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
echo |set /p="99 " & TextAnalyzer.exe  "(◊(p V q) Λ (◊p V ◊q)) V (p → ~q)" 4 | findstr /C:"A: Satisfiable"		& IF ERRORLEVEL 1 ( echo ###### ANSWER INCORRECT ###### )
																				